from tkinter import*
a=Tk()
a.title("Basic FOrm Page")
l1=Label(a,text="Name:")
l2=Label(a,text="Email:")
l3=Label(a,text="Phone:")
l4=Label(a,text="Address:")
l5=Label(a,text="Post Card:")
l6=Label(a,text="contry:")
l7=Label(a,text="CardNum:")
l8=Label(a,text="Security Code:")
l9=Label(a,text="Country:")
b1=Button(a,text="Enter",bg="blue",fg="red")
cv=("india","USA","Australia","Japan")
ab=StringVar()
xx=OptionMenu(a,ab,*cv)
xx.config(width=15)
ab.set("choose country")
e1=Entry(a)
e2=Entry(a)
e3=Entry(a)
e4=Entry(a)
e5=Entry(a)
e6=Entry(a)
e7=Entry(a)
e8=Entry(a)
l1.grid(row=0,column=0)
e1.grid(row=0,column=1)
l2.grid(row=1,column=0)
e2.grid(row=1,column=1)
l3.grid(row=2,column=0)
e3.grid(row=2,column=1)
l4.grid(row=3,column=0)
e4.grid(row=3,column=1)
l5.grid(row=4,column=0)
e5.grid(row=4,column=1)
l6.grid(row=5,column=0)
e6.grid(row=5,column=1)
l7.grid(row=6,column=0)
e7.grid(row=6,column=1)
l8.grid(row=7,column=0)
e8.grid(row=7,column=1)
l9.grid(row=8,column=0)
xx.grid(row=8,column=1)
b1.grid(row=9,column=1)
mainloop()
